# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # A/B testing in a marketplace — does a product page redesign increase AOV?
#
# **Portfolio project · CRISP-DM methodology · Brazilian E-Commerce by Olist dataset**
#
# This notebook is the **presentation layer**: it reads the results generated by the pipeline and tells
# the story. **It computes nothing.** All the computation lives in `src/` and is run with a single
# command:
#
# ```bash
# python run_all.py      # ~5 min, fixed seeds -> deterministic result
# ```
#
# `run_all.py` runs the 6 CRISP-DM phases in order, verifies each output and finishes with a
# reproducibility report. This notebook assumes it has already been run.
#
# > **Note on methodological honesty.** The Olist dataset does not come with control/treatment
# > groups. The assignment is **simulated** and the treatment effect is **injected in a declared
# > way** (diluted model: 20% of the treated units respond with +25%, mean effect +5%). The goal is
# > **not** to discover whether the redesign works — we know it does, because we are the ones who
# > put the effect there — but to **demonstrate that the design and the analysis control false
# > positives and recover an effect of known size without bias**. That is the competency being
# > assessed in an experimentation role.

# %%
import json
import os
import sys
from pathlib import Path

if Path.cwd().name == "notebooks":
    os.chdir("..")
sys.path.insert(0, "src")

import pandas as pd
from IPython.display import Image, display

import config

TABLES = config.OUT_TABLES
FIGURES = config.OUT_FIGURES


def rj(name):
    return json.loads((TABLES / name).read_text(encoding="utf-8"))


def L(x):
    return [round(float(v), 3) for v in x]


_needed = ["phase2_summary.json", "phase3_balance.csv", "phase3_srm.csv",
           "phase4_summary.json", "phase5_summary.json"]
_missing = [f for f in _needed if not (TABLES / f).exists()]
if _missing:
    raise SystemExit(f"Missing results {_missing}. Run first:  python run_all.py")
print("Results found. Project parameters:")
print(" ", config.summary())

# %% [markdown]
# ---
# ## Phase 1 — Business Understanding
#
# **Context.** Olist is a marketplace that connects small Brazilian sellers with large online
# sales channels. The Product team proposes a **product page redesign** (cross-sell
# recommendations + progress bar toward free shipping) with the hypothesis that it **increases
# the average order value (AOV)** without harming satisfaction or increasing cancellations.
#
# **Structural limitation (scope decision).** The dataset starts at the order: there are no
# sessions or carts -> **conversion cannot be measured**. The primary metric is the **AOV**.
#
# | Element | Definition |
# |---|---|
# | **H0** | μ_treatment − μ_control = 0 |
# | **H1** | μ_treatment − μ_control ≠ 0 (two-tailed, α = 0.05) |
# | **Primary metric** | AOV = Σ `order_items.price` per order (merchandise value) |
# | **Guardrails** | G1 review_score · G2 cancellation · G3 freight · G4 number of items — **two-gate** rule (significant **AND** magnitude) + Benjamini-Hochberg correction |
# | **Relevance MDE** | **+3%** — *derived* from a break-even model (`src/mde_cost_model.py`) |
# | **Decision rule** | LAUNCH if p < 0.05 **and** 95% CI of the lift entirely above +3% **and** no guardrail degraded; ITERATE if significant but the CI touches the MDE; DO NOT LAUNCH otherwise |
#
# Detail: `docs/01_business_understanding.md`.

# %%
print("Declared parameters (params.yaml -> src/config.py):")
print(f"  seed               : {config.SEED}")
print(f"  alpha (two-tailed) : {config.ALPHA}")
print(f"  diluted effect     : {config.P_RESP:.0%} responds with +{config.DELTA_RESP:.0%}"
      f"  ->  ATE = +{config.ATE:.0%}")
print(f"  relevance MDE      : +{config.MDE_RELEVANCIA:.0f}%")
print(f"  time window        : {config.WINDOW_START} .. {config.WINDOW_END}")

# %% [markdown]
# ---
# ## Phase 2 — Data Understanding
#
# Dataset: [Brazilian E-Commerce by Olist](https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce)
# · **CC BY-NC-SA 4.0** license (verified on download) · ~100k orders · 9 relational tables.

# %%
f2 = rj("phase2_summary.json")
aov = f2["AOV_merch_value"]
logaov = f2["AOV_log_merch"]
print("PRIMARY METRIC — AOV (merchandise value per order)")
print(f"  n = {aov['n']:,}   mean = R$ {aov['mean']:.2f}   median = R$ {aov['median']:.2f}")
print(f"  CV = {aov['cv']:.3f}   skew = {aov['skew']:.1f}   excess kurtosis = {aov['kurtosis_excess']:.0f}")
print(f"  log(AOV): skew = {logaov['skew']:.2f}   kurtosis = {logaov['kurtosis_excess']:.2f}  (robust range)")
print(f"\n  {f2['orders_per_customer']['pct_customers_1_order']:.1f}% of customers with just 1 order "
      f"-> randomization unit ≈ analysis unit")
print("  Reading: AOV is highly skewed; at large n the mean is normal by the CLT -> Welch-t primary.")
display(Image(str(FIGURES / "f2_02_aov_distribution.png")))

# %% [markdown]
# **Validity limitations** (`docs/02_data_understanding.md` §2.7): no real randomization or traffic
# layer; declared injected effect; historical window of 2 years (not a 2-4 week experiment);
# ~3% repeat purchase -> no retention metric; single market.

# %% [markdown]
# ---
# ## Phase 3 — Data Preparation
#
# Cleaning aimed at the experimental question. Every step is traced.
# Decisions: 2017-01/2018-08 window · review dedup by timestamp · **dedup to 1 order/customer**
# (moves the AOV only -0.35%) · **p99.5 winsorization only for the significance test**.

# %%
display(pd.read_csv(TABLES / "phase3_transformations.csv"))

# %%
bal = pd.read_csv(TABLES / "phase3_balance.csv")
srm = pd.read_csv(TABLES / "phase3_srm.csv").iloc[0]
display(bal[["covariate", "type", "SMD", "p_value", "balanced"]])
print(f"All |SMD| < 0.10: {bal['balanced'].all()}   ·   no omnibus test significant: "
      f"{(bal['p_value'] >= 0.05).all()}")
print(f"SRM check: control={srm['n_control']} treatment={srm['n_treatment']}  "
      f"chi2={srm['chi2']:.3f} p={srm['p_value']:.3f}  ->  {srm['veredicto']}")
display(Image(str(FIGURES / "f3_01_balance.png")))

# %% [markdown]
# ---
# ## Phase 4 — Modeling (statistical design of the experiment)

# %%
f4 = rj("phase4_summary.json")
pw = f4["1_power_analysis"]
print("POWER ANALYSIS")
for k in ("raw", "winsor_p99.5"):
    r = pw[k]
    print(f"  [{k:12}] detectable MDE at 80% = +{r['mde_rel_detectable_80pct_pct']}%   "
          f"power(ATE=+5%) = {r['power_diluted_effect_+5pct_ATE']}   "
          f"mean lift (1000 sims) = {r['mean_estimated_lift_sim_pct']}%  (bias {r['estimator_bias_pp']} pp)")
print(f"\n  Power penalty from the diluted effect: "
      f"{pw['raw']['power_penalty_from_dilution_pp']} pp -> negligible "
      f"(the AOV's natural variance, CV≈1.5, dominates).")
display(Image(str(FIGURES / "f4_04_power_vs_n.png")))

# %%
asm = f4["2_assumptions"]
print("ASSUMPTION CHECKS")
print(f"  Normality of the raw data      : p = {asm['normality_raw_data']['p']}  (not normal, as expected)")
print(f"  Normality of the mean (CLT)    : p = {asm['normality_bootstrap_mean']['p']}  -> Welch-t valid")
print(f"  Homoscedasticity WITHOUT effect: Levene p = {asm['homoscedasticity_no_effect']['p']}")
print(f"  Homoscedasticity WITH effect   : Levene p = {asm['homoscedasticity_diluted_effect']['p']}"
      f"  -> unequal variances under H1 -> use Welch, NOT Student")
display(Image(str(FIGURES / "f4_01_clt_normality.png")))

# %%
print("A/A CALIBRATION  (2,000 random partitions, no effect)")
for k, v in f4["3_aa_calibration"].items():
    print(f"  [{k:14}] false positives = {v['false_positive_rate_alpha_0.05']:.3f}  "
          f"(95% CI {L(v['CI95_rate'])})  ·  KS vs. uniform p = {v['KS_vs_uniform_p']:.3f}  ->  {v['verdict']}")
display(Image(str(FIGURES / "f4_02_aa_pvalues.png")))

# %%
p = f4["4_ab_test"]["primary"]
print("A/B TEST  —  injected diluted effect (SEED=42)")
print(f"  Welch · winsor AOV : +{p['Welch_winsor_p99.5']['lift_rel_pct']}%  "
      f"95% CI {L(p['Welch_winsor_p99.5']['CI95_lift_pct'])}%  ·  p = {p['Welch_winsor_p99.5']['p_value']}")
print(f"  Welch · raw AOV    : +{p['Welch_raw']['lift_rel_pct']}%  {L(p['Welch_raw']['CI95_lift_pct'])}%")
print(f"  bootstrap (10k)    : {L(p['bootstrap_ratio']['CI95_lift_pct'])}%")
print(f"  the true effect (+5%) is within the CI: {p['Welch_winsor_p99.5']['ATE_5pct_in_CI']}")
print("\n  GUARDRAILS (Benjamini-Hochberg):")
for g, v in f4["4_ab_test"]["guardrails"].items():
    print(f"    {g:20}  BH-adjusted p = {v['p_adjusted_BH']:.3f}  ->  degraded: {v['significant_after_BH']}")
display(Image(str(FIGURES / "f4_03_ab_effect.png")))

# %% [markdown]
# ### Phase 4 · additional robustness (global audit improvements)

# %%
ms = f4["8_ab_multiseed"]
print("MULTI-SEED A/B (500 replicates: re-split + re-injection)")
for k in ("raw", "winsor_p99.5"):
    m = ms[k]
    print(f"  [{k:12}] mean lift = {m['mean_lift_pct']}%   bias = {m['bias_pp']} pp   "
          f"95% CI coverage of +5% = {m['CI95_coverage_of_+5pct']}")
print("  -> RAW is UNBIASED and has nominal coverage; winsorization introduces -0.36 pp of bias.")

gr = f4["6_guardrail_regression"]
print("\nREGRESSION INJECTED INTO G1 (two-gate rule: significant AND magnitude >= 0.05)")
for s in gr["scenarios"]:
    print(f"  injected {s['regression_injected_pts']:+.2f} pts -> p={s['p_value']:.1e}   "
          f"blocks (AND rule): {s['rule_AND_(significant_AND_magnitude)']}")
print("  -> at large n EVERYTHING is significant; the rule needs the magnitude gate.")

het = f4["7_heterogeneous_effect"]
print(f"\nVARIANT WITH A REAL HETEROGENEOUS EFFECT (concentrated below R$ {het['free_shipping_threshold_R$']:.0f})")
print(f"  lift within band = {het['lift_in_band_pct']}%   outside = {het['lift_outside_band_pct']}%   "
      f"interaction p = {het['p_interaction_near_threshold_HC3']}")
print("  -> the segment analysis DOES detect heterogeneity when it exists.")

cl = f4["9_clustered_se"]
print("\nALL ORDERS + CUSTOMER-CLUSTERED SE")
print(f"  lift = {cl['lift_pct_all_orders']}%  (dedup: {cl['lift_pct_dedup_1_order_per_customer_ref']}%)   "
      f"·  clustering inflates the SE by only {cl['SE_inflation_from_clustering_pct']}%")

# %% [markdown]
# ### Phase 4 · relevance MDE derived from a cost model
#
# The +3% is not asserted: it is the *break-even* of the redesign (incremental margin = cost of ownership).

# %%
_mde = pd.read_csv(TABLES / "mde_cost_model.csv")
display(_mde.pivot(index="pedidos_anio", columns="horizonte_payback_anios", values="MDE_breakeven_pct"))
print("The +3% is valid for a marketplace with >= ~415,000 orders/year (2-year payback).")
display(Image(str(FIGURES / "f_mde_breakeven.png")))

# %% [markdown]
# ---
# ## Phase 5 — Evaluation

# %%
f5 = rj("phase5_summary.json")
prim, imp, anc = f5["1_primary_result"], f5["2_business_impact"], f5["3_ancova"]
print("SIGNIFICANCE vs RELEVANCE")
print(f"  Primary effect  : +{prim['lift_pct']}%   95% CI {L(prim['CI95_lift_pct'])}%   log10(p) = {prim['log10_p']}")
print(f"  Significant?    : {prim['significant']}")
print(f"  CI entirely above the +3% MDE?  : {prim['ci_entirely_above_MDE']}   ->  RELEVANT: {prim['relevant']}")
print(f"\n  ANCOVA (covariate adjustment): +{anc['adjusted']['lift_pct']}%  "
      f"95% CI {L(anc['adjusted']['ci95_pct'])}%  ·  SE -{anc['SE_reduction_pct']}%")
print("\nESTIMATED ECONOMIC IMPACT")
print(f"  Merchandise GMV uplift : +R$ {imp['uplift_GMV_annual_R$']:,}/year  "
      f"(CI [{imp['uplift_GMV_annual_CI95_R$'][0]:,}, {imp['uplift_GMV_annual_CI95_R$'][1]:,}])")
print(f"  ≈ +R$ {imp['uplift_marketplace_revenue_annual_R$_assuming_15pct_commission']:,}/year of commission (15%)")

# %%
print("PRE-SPECIFIED SEGMENTS — log(AOV) interaction, HC3 Wald, + Benjamini-Hochberg")
for k, v in f5["4_segments"]["interaction_test"].items():
    print(f"  {k:14}  raw p = {v['p_raw']:.3f}   BH p = {v['p_BH']:.3f}   "
          f"heterogeneous: {v['heterogeneity_significant_after_BH']}")
print("\nP-HACKING — 38 exploratory cuts (expected by chance ≈ 1.9)")
ph = f5["5_p_hacking"]
for esc in ("test_at_LEVEL_(mv_w)", "test_at_LOG_(relative_effect)"):
    s = ph[esc]
    print(f"  {esc:32}  nominal = {s['nominal_p<0.05']['n']}   after BH = {s['after_BH']['n']}   "
          f"after Bonferroni = {s['after_Bonferroni']}")
print("  -> on the wrong scale (level) the artifacts of the multiplicative effect survive")
print("     Bonferroni; on the correct scale (log) nothing survives. Correcting does not save a bad estimand.")
display(Image(str(FIGURES / "f5_01_forest_segments.png")))

# %%
dec = f5["6_decision"]
print("=" * 60)
print(f"  PRODUCT DECISION:  {dec['decision']}")
print("=" * 60)
for j in dec["justification"]:
    print(f"  • {j}")
print("\n  Caveats:")
for cv in dec["caveats"]:
    print(f"  • {cv}")

# %% [markdown]
# ---
# ## Phase 6 — Deployment
#
# - **Executive summary (1 page, non-technical):** `docs/executive_summary.md`
# - **Repository README** · **LinkedIn post draft:** `docs/linkedin_post.md`
# - **Per-phase documentation:** `docs/0X_*.md`
# - **Audits:** `docs/audit_phase1_phase2.md` · `docs/audit_phase5.md` ·
#   `docs/audit_global.md` (26 decisions + 6 improvements applied)
#
# ### Reproducibility
#
# - Single entrypoint: **`python run_all.py`** (verifies invariants and exits with an error if something doesn't check out).
# - Parameters in **`params.yaml`** (single source of truth, loaded by `src/config.py`).
# - Tests: **`pytest`** (fast) · **`pytest -m slow`** (re-runs and checks idempotency).
# - This notebook **only reads** `outputs/`; there is no parallel execution path.
#
# ### What this project demonstrates
#
# 1. **Complete experimental design**: hypothesis, single primary metric, two-gate guardrails,
#    **MDE derived from a cost model**, decision rule — *before* looking at the data.
# 2. **A priori power analysis** + **empirical verification**: A/A (2,000 partitions, 5% false
#    positives) and **multi-seed A/B** (500, unbiased estimator on raw data).
# 3. **Assumption checks** that change the chosen test (heteroscedasticity under H1 → Welch).
# 4. **Statistical significance vs. business relevance**, with impact in R$.
# 5. **P-hacking control**: pre-specification, multiplicity correction, and the demonstration that
#    the wrong scale for the estimand fabricates findings that not even Bonferroni removes.
# 6. **Methodological honesty**: the effect is synthetic and declared; the project validates the *process*.
